/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AuthRouteImport } from './pages/_auth'
import { Route as LoginRouteImport } from './pages/login'
import { Route as AuthAdminRouteImport } from './pages/_auth/admin'
import { Route as AuthDashboardRouteImport } from './pages/_auth/dashboard'
import { Route as AuthAdminIndexRouteImport } from './pages/_auth/admin/index'
import { Route as AuthAdminClinicRouteImport } from './pages/_auth/admin/clinic'
import { Route as AuthAdminDoctorTypesRouteImport } from './pages/_auth/admin/doctor-types'
import { Route as AuthAdminDoctorsRouteImport } from './pages/_auth/admin/doctors'
import { Route as AuthAdminServicesRouteImport } from './pages/_auth/admin/services'
import { Route as AuthPatientsIndexRouteImport } from './pages/_auth/patients/index'
import { Route as AuthPatientsPatientIdRouteImport } from './pages/_auth/patients/$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminClinicRoute = AuthAdminClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminDoctorTypesRoute = AuthAdminDoctorTypesRouteImport.update({
  id: '/doctor-types',
  path: '/doctor-types',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminDoctorsRoute = AuthAdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminServicesRoute = AuthAdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthPatientsIndexRoute = AuthPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientsPatientIdRoute = AuthPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/admin/clinic': typeof AuthAdminClinicRoute
  '/admin/doctor-types': typeof AuthAdminDoctorTypesRoute
  '/admin/doctors': typeof AuthAdminDoctorsRoute
  '/admin/services': typeof AuthAdminServicesRoute
  '/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/patients/': typeof AuthPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/admin/clinic': typeof AuthAdminClinicRoute
  '/admin/doctor-types': typeof AuthAdminDoctorTypesRoute
  '/admin/doctors': typeof AuthAdminDoctorsRoute
  '/admin/services': typeof AuthAdminServicesRoute
  '/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/admin': typeof AuthAdminIndexRoute
  '/patients': typeof AuthPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/admin/clinic': typeof AuthAdminClinicRoute
  '/_auth/admin/doctor-types': typeof AuthAdminDoctorTypesRoute
  '/_auth/admin/doctors': typeof AuthAdminDoctorsRoute
  '/_auth/admin/services': typeof AuthAdminServicesRoute
  '/_auth/patients/$patientId': typeof AuthPatientsPatientIdRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/patients/': typeof AuthPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/admin/clinic'
    | '/admin/doctor-types'
    | '/admin/doctors'
    | '/admin/services'
    | '/patients/$patientId'
    | '/admin/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin/clinic'
    | '/admin/doctor-types'
    | '/admin/doctors'
    | '/admin/services'
    | '/patients/$patientId'
    | '/admin'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/admin'
    | '/_auth/dashboard'
    | '/_auth/admin/clinic'
    | '/_auth/admin/doctor-types'
    | '/_auth/admin/doctors'
    | '/_auth/admin/services'
    | '/_auth/patients/$patientId'
    | '/_auth/admin/'
    | '/_auth/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/clinic': {
      id: '/_auth/admin/clinic'
      path: '/clinic'
      fullPath: '/admin/clinic'
      preLoaderRoute: typeof AuthAdminClinicRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/doctor-types': {
      id: '/_auth/admin/doctor-types'
      path: '/doctor-types'
      fullPath: '/admin/doctor-types'
      preLoaderRoute: typeof AuthAdminDoctorTypesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/doctors': {
      id: '/_auth/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AuthAdminDoctorsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/services': {
      id: '/_auth/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthAdminServicesRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/patients/': {
      id: '/_auth/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthPatientsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patients/$patientId': {
      id: '/_auth/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthPatientsPatientIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminClinicRoute: typeof AuthAdminClinicRoute
  AuthAdminDoctorTypesRoute: typeof AuthAdminDoctorTypesRoute
  AuthAdminDoctorsRoute: typeof AuthAdminDoctorsRoute
  AuthAdminServicesRoute: typeof AuthAdminServicesRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminClinicRoute: AuthAdminClinicRoute,
  AuthAdminDoctorTypesRoute: AuthAdminDoctorTypesRoute,
  AuthAdminDoctorsRoute: AuthAdminDoctorsRoute,
  AuthAdminServicesRoute: AuthAdminServicesRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthPatientsPatientIdRoute: typeof AuthPatientsPatientIdRoute
  AuthPatientsIndexRoute: typeof AuthPatientsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthPatientsPatientIdRoute: AuthPatientsPatientIdRoute,
  AuthPatientsIndexRoute: AuthPatientsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
